export const ActionTypes = {
  UPDATE_STATE: "UPDATE_STATE",
  MODIFY_ATTRIBUTE_POINTS: "MODIFY_ATTRIBUTE_POINTS",
  MODIFY_SKILL_SPENDING: "MODIFY_SKILL_SPENDING",
  ADD_NEW_CHARACTER: "ADD_NEW_CHARACTER",
}



