export const initialState = [
  {
    id: 0,
    totalPoints: 0,
    attributes: {
      Strength: 0,
      Dexterity: 0,
      Constitution: 0,
      Intelligence: 0,
      Wisdom: 0,
      Charisma: 0,
    },
    classes: {
      Barbarian: false,
      Wizard: false,
      Bard: false,
    },
    modifiers: {
      Strength: -5,
      Dexterity: -5,
      Constitution: -5,
      Intelligence: -5,
      Wisdom: -5,
      Charisma: -5,
    },
    skills: {
      Acrobatics: 0,
      Animal_Handling: 0,
      Arcana: 0,
      Athletics: 0,
      Deception: 0,
      History: 0,
      Insight: 0,
      Intimidation: 0,
      Investigation: 0,
      Medicine: 0,
      Nature: 0,
      Perception: 0,
      Performance: 0,
      Persuasion: 0,
      Religion: 0,
      Sleight_of_Hand: 0,
      Stealth: 0,
      Survival: 0,
    },
    skillsSpending: {
      Acrobatics: 0,
      Animal_Handling: 0,
      Arcana: 0,
      Athletics: 0,
      Deception: 0,
      History: 0,
      Insight: 0,
      Intimidation: 0,
      Investigation: 0,
      Medicine: 0,
      Nature: 0,
      Perception: 0,
      Performance: 0,
      Persuasion: 0,
      Religion: 0,
      Sleight_of_Hand: 0,
      Stealth: 0,
      Survival: 0,
    },
  },
];
